package fr.graynaud.eu4saveconverter.controller;

public enum ErrorCode {
    DEFAULT_ERROR, PASSWORD_NOT_MATCH_REGEX, PASSWORDS_NOT_MATCH, SAME_PASSWORD, INVALID_CREDENTIALS, KEY_NOT_FOUND,
    LOGIN_ALREADY_EXIST, NOT_AUTHENTICATED, LOGIN_NOT_MATCH_REGEX, PATH_ALREADY_EXIST, CAMPAIGN_NOT_FOUND, KEY_EXPIRED
}
